name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu version20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Deploy to Staging
        run: npm run deploy-staging
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: npm run deploy-production
