name: Android CI/CD
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu 20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java
    
      with:
        java-version: '11'
        distribution: 'sdk'
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
    - name: Build and Test
      run: ./gradlew clean build
    - name: Archive APKS
      run: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug